### ISSUE TITLE
Pkcs5

### ISSUE THREAD

**Issue by Marthianfred** [marspere/goencrypt#1]
goencrypt.Pkcs5?? not found only dysplay goencrypt.Pkcs7

**Comment by marspere** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Marthianfred** [comment]
> 这是来自QQ邮箱的假期自动回复邮件。   您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

i dont understand

**Comment by marspere** [comment]
PKCS7 is compatible with PKCS5
