### ISSUE TITLE
hash only hex

### ISSUE THREAD

**Issue by Marthianfred** [marspere/goencrypt#2]
php hash 256 sample

`$keyhash = hash("sha256", $key, true);`

this return ����ERH����QW�ɿ�bܪ�ړ�2�ٓ;��

how to i can emulated this condictions 
i try implemente AES ECB PKCS5Padding with return hash binary 
with this library its posible this..????

scenario

`key, err := goencrypt.SHA(goencrypt.SHA256,[]byte(Utils.APIKEY))
	if err != nil {
		fmt.Println(err)
	}

	k :=fmt.Sprintf("%.*s\n",16,  key)
	
	cipher, err := goencrypt.NewAESCipher([]byte(k), []byte(k), goencrypt.ECBMode, goencrypt.Pkcs7 , goencrypt.PrintBase64)
	if err != nil {
		fmt.Println(err)
	}

	cipherText, err := cipher.AESEncrypt([]byte("834"))
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(cipherText)
	plainText, err := cipher.AESDecrypt(cipherText)
	fmt.Println(plainText)`

prints this

`
IV length must equal block size
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x529a8f]
`

**Comment by marspere** [comment]
Before the v1.0.7 version, the default output format of the SHA method is hexadecimal encoding. After the v1.0.7 version, the output format options are exposed to the outside world. The options are base64, hex and the default no encoding.
You can choose v1.0.7 and later versions, choose not to encode the result, and you will get the effect you want.
